inherit_from: .rubocop_todo.yml

Style/AccessorMethodName:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

#see https://github.com/bbatsov/rubocop/issues/1747
Style/SpecialGlobalVars:
  Enabled: false

#this folder contains functions returning arrays of data, so functions will be long
Metrics/AbcSize:
  Exclude:
    - 'lib/cartocss_helper/style_specific/**/*'

Metrics/MethodLength:
  Exclude:
    - 'lib/cartocss_helper/style_specific/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'lib/cartocss_helper/style_specific/**/*'
