inherit_gem:
  matkoniecz-ruby-style:
    - standard_rubocop_config.yml

#failed to detect anything useful here
Style/IdenticalConditionalBranches:
  Exclude:
    - 'lib/cartocss_helper/visualise_changes_diff_from_images.rb'

#this folder contains functions returning arrays of data, so functions will be long
Metrics/AbcSize:
  Exclude:
    - 'lib/cartocss_helper/style_specific/**/*'

Metrics/MethodLength:
  Exclude:
    - 'lib/cartocss_helper/style_specific/**/*'
    - 'lib/data/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'lib/cartocss_helper/style_specific/**/*'

Metrics/LineLength:
  Exclude:
    - 'cartocss_helper.gemspec'
