inherit_from: .rubocop_todo.yml

Style/AccessorMethodName:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Style/ClassVars:
  Enabled: false

#? I am not sure...
Style/BracesAroundHashParameters:
  Enabled: false

#syntactic sugar without gain
Style/NonNilCheck:
  Enabled: false

#see https://github.com/bbatsov/rubocop/issues/1747
Style/SpecialGlobalVars:
  Enabled: false

#affected by rubocop bug
Style/GuardClause:
  Enabled: false

#this folder contains functions returning arrays of data, so functions will be long
Metrics/AbcSize:
  Exclude:
    - 'lib/cartocss_helper/style_specific/**/*'

Metrics/MethodLength:
  Exclude:
    - 'lib/cartocss_helper/style_specific/**/*'
    - 'lib/data/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'lib/cartocss_helper/style_specific/**/*'
