inherit_from: .rubocop_todo.yml

Naming/AccessorMethodName:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Style/ClassVars:
  Enabled: false

Lint/UnusedMethodArgument:
  AutoCorrect: False

#false positive
Naming/VariableName:
  Enabled: false

#? I am not sure...
Style/BracesAroundHashParameters:
  Enabled: false

#? I am not sure...
Style/RaiseArgs:
  Enabled: false

#? I am not sure...
Naming/PredicateName:
  Enabled: false

#? I am not sure...
Style/NilComparison:
  Enabled: false

#? I am not sure...
Style/RegexpLiteral:
  Enabled: false

#? I am not sure...
Style/ZeroLengthPredicate:
  Enabled: false

#not impressed by proposed changes, but maybe it was a bad luck
Style/UnneededInterpolation:
  Enabled: false

#not impressed by proposed changes, but maybe it was a bad luck
Style/SymbolProc:
  Enabled: false

#failed to detect anything useful here
Style/IdenticalConditionalBranches:
  Exclude:
    - 'lib/cartocss_helper/visualise_changes_diff_from_images.rb'

#syntactic sugar without gain
Style/NonNilCheck:
  Enabled: false

# see https://github.com/bbatsov/rubocop/issues/1747#issuecomment-223370141
# this auto-correct rule may break things and is not a clear improvement
Style/SpecialGlobalVars:
  Enabled: false

#affected by rubocop bug
Style/GuardClause:
  Enabled: false

#this folder contains functions returning arrays of data, so functions will be long
Metrics/AbcSize:
  Exclude:
    - 'lib/cartocss_helper/style_specific/**/*'

Metrics/MethodLength:
  Exclude:
    - 'lib/cartocss_helper/style_specific/**/*'
    - 'lib/data/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'lib/cartocss_helper/style_specific/**/*'

Metrics/LineLength:
  Exclude:
    - 'cartocss_helper.gemspec'

