language: ruby
rvm:
  - 2.1
  - 2.2 
  - 2.3.0
  - 2.3.1

# https://docs.travis-ci.com/user/caching/
cache: bundler

# https://github.com/wbzyl/ruby-intro/blob/master/.travis.yml
script: bundle exec rspec