language: ruby
rvm:
  - 2.1
  - 2.2 
  - 2.3.0
  - 2.3.1

# https://docs.travis-ci.com/user/caching/
cache: bundler

# https://github.com/wbzyl/ruby-intro/blob/master/.travis.yml
script: bundle exec rspec

addons:
  code_climate:
    repo_token:
      secure: ODhyL7h1ykPX3qVWQdfyORul38CMBP5VLjCjCi6OStVYfWaSau9Uycg4pBnNrHDzm+ugdKXO2MiyU5fwzf9CVz6Cd9IeXW4kqvsLqBwRGMSvUbL9HK/BTkTxonLrWhg2M5iqMPQAzudnQJJSoKmSNV8q5ygtz2mlkCyW+Ppc+jaFWDcKePvLF+OCLconyDAkCpiwl5oP2KL9bGxoiaIpYspjB9SZiUA1wptUmDN5lGb+kByEqP60VD4pQtD4iE/ct2gYV5so5o9YtKJBcPo5UggpM6Zj7Rf0PnjEsc3ztvRWS/BLnLM91txqnrdIsQik3ZUrW1QTFNZEC/8GnedmOIOfYK7SNGnbM04O3GH8rNnsnMEXKdmTmXrZouK3mA4bcMMPfV7xL4oFFhAxlxRoLpdjfhh2mzwU63lddIP+39CcSzy3xYL1K97sQi258bQtp07pXvx5HZCgZW96D2eQsw+9kFtEvuFKDL3rSXO0wYBujbOEdiX0+ekIzbYJmoIOg3Yx0zwqchNrItKGtWUnEWGu1cHZOAHa5hWJ+WtA4VxznyqwGQSGkmLTSqFBr4ILTS/CS/GvQJNNiwo5hE0nH5X1drxNxm6HdEVgcCFtxenlyIdF9yB/ljGjqzqJLV8QSeqXx+pK0hCVKLEFp3GdEu5cQQNFAe0Uv1sPDD+1fU8=
